housei/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

housei/bbs/urls.py
from .models import Article
from django.views import generic # Second add
from django.urls import path
from . import views

app_name = 'bbs'

urlpatterns = [
    path('home/', views.Index.as_view(), name='home'),
    path('list/', views.IndexView.as_view(), name='list'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

housei/housei/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='bbs/home')),
    path('index.html', RedirectView.as_view(url='bbs/home')),
    path('bbs/', include('bbs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

housei/accounts/models.py
from django.db import models

# Create your models here.

housei/bbs/models.py
from django.db import models
from django.urls import reverse

class Article(models.Model):
    title = models.CharField(max_length = 200)
    content = models.TextField(max_length=1000)

    author = models.ForeignKey(
        'auth.User',
        on_delete = models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('bbs:detail', kwargs={'pk': self.pk})

housei/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

housei/bbs/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Article
from django.views import generic

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.views.generic import TemplateView

class Index(TemplateView):
    template_name = "bbs/index.html"

class IndexView(generic.ListView):
    model = Article
 
class DetailView(generic.DetailView):
    model = Article

class CreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Article
    fields = ['content', 'title', ]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CreateView, self).form_valid(form)

class UpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Article
    fields = ['content', 'title', ]
 
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
 
        if obj.author != self.request.user:
            raise PermissionDenied('You do not have permission to edit.')
 
        return super(UpdateView, self).dispatch(request, *args, **kwargs)

class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Article
    success_url = reverse_lazy('bbs:list')

housei/accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block content %}
<h1>ユーザー登録</h1>
<section class='common-form'>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>登録</button>
    </form>
</section>
{% endblock %}

housei/bbs/templates/bbs/Index.html
{% extends 'layout.html' %}
 
{% block content %}


<div class="contents">
    <div class="contents-item">
        <h2 class="contents-title">
            イベント・ニュース
        </h2>
        <img class="contents-img" src="/static/img/news.png" alt="ニュース">
            <ul class="contents-exp">
<li>
            2023年5月13日 味波で同窓会しました!<br>
            大盛況!!
</li>
<li>
            2023年年末にも歳忘れ同窓会しようぜ!!!<br>
            楽しい同窓会になるといいね！
</li>
            </ul>
    </div>
    <div class="contents-item">
        <h2 class="contents-title">
            みんなのワイワイ掲示板
        </h2>
        <img class="contents-img" src="/static/img/keijiban.png" alt="掲示板">
            <ul class="contents-exp">
<li>
            懐かしい仲間と気軽になんでも話そう!!<br>
            
</li>
<li>
            近況など教えてね<br>
</li>
</ul>
</p>
</div>
    <div class="contents-item">
        <h2 class="contents-title">
            お宝映像・写真
        </h2>
        <img class="contents-img" src="/static/img/gazo.png " alt="画像">
            <ul class="icontents-exp">
<li>
            懐かしい仲間と気軽になんでも話そう!!<br>
            
</li>
<li>
            近況など教えてね<br>
</li>
            </ul>
    </div>
</div>

 
{% endblock %}

housei/bbs/templates/bbs/article_confirm_delete.html
{% extends 'layout.html' %}

{% block content %}

<h1>投稿の削除</h1>
<p>以下を削除しますか?</p>
<p>{{ article.content }}</p>
<p>{{ article.user_name }}</p>
<p>{{ article.author }}</p>
<p>{{ article.created_at|date:"Y-m-j H:i:s" }}</p>
<p>{{ article.updated_at|date:"Y-m-j H:i:s" }}</p>

<form action='' method='post'>{% csrf_token %}
    <a href='JavaScript:history.back()' class='btn btn-outline-primary'>削除しないで戻る</a>
    <button type='submit' class='submit delete btn btn-danger'>削除する</button>
</form>

{% endblock %}

housei/bbs/templates/bbs/article_detail.html
{% extends 'layout.html' %}

{% block content %}

<div>
    <p>タイトル：{{ article.title }}</p>
    <p>投稿内容：<br>{{ article.content }}</p>
    <p>{{ article.author }}</p>
    <p>{{ article.created_at|date:"Y-m-j H:i:s" }}<br>
    {{ article.updated_at|date:"Y-m-j H:i:s" }}</p>
</div>
<div class='mt-4'>
    {% if request.user.id == object.author_id %}
    <a href='{% url "bbs:update" article.pk %}'  class='btn btn-outline-primary mr-2'>編集</a>
    {% endif %}

    <a href='{% url "bbs:list" %}' class='btn btn-outline-primary'>一覧に戻る</a>

    {% if request.user.id == object.author_id %}
    <a href='{% url "bbs:delete" article.pk %}'  class='btn btn-danger ml-5'>削除</a>
    {% endif %}
</div>
{% endblock %}

housei/bbs/templates/bbs/article_form.html
{% extends 'layout.html' %}

{% block content %}

<h1 class="mt-3 mb-4">{{ object|yesno:'投稿内容の更新,新規投稿の作成'}}</h1>

<form action='' method='post'>
    {% csrf_token %}
    <p>タイトル：{{ form.title }}</p>
    <p>本文：<br>
    {{ form.content }}</p>
    <button type='submit' class='submit btn btn-outline-primary'>{{ object|yesno:'更新,作成'}}</button>
</form>
<div class="mt-3">
    <a href='JavaScript:history.back()' class='btn btn-outline-primary'>< 戻る</a>
</div>

{% endblock %}

housei/bbs/templates/bbs/article_list.html
{% extends 'layout.html' %}
 
{% block content %}
 
    <h1 class="mt-3 mb-4">投稿一覧</h1>
 
    <table class='table table-striped table-hover'>
        <tr>
            <th>投稿者</th>
            <th>内容</th>
        </tr>
        {% for article in object_list %}
        <tr>
            <td>
                <a href='{% url "bbs:detail" article.pk %}'>{{ article.title }} {{ article.author }}</a><br>
                作成日時：{{ article.created_at|date:"Y-m-j H:i" }}<br>
                更新日時：{{ article.updated_at|date:"Y-m-j H:i" }}
            </td>
            <td>{{ article.content }}</td>
        </tr>
        {% endfor %}
    </table>
	{% if user.is_authenticated %}
    <p>
        <a href='{% url "bbs:create" %}'  class='btn btn-outline-primary'>新規投稿</a>
    </p>
    {% endif %} 
{% endblock %}

housei/bbs/templates/bbs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--- <link rel="stylesheet" href="{% static 'css/style.css' %}"> --->
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
    <style>body {padding-top: 80px;}</style>
    <title>豊正中学校1974年度卒業同窓会</title>
</head>
<body>
    <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
        <a class='navbar-brand' href='{% url "bbs:index" %}'>BBS TOP</a>
    </nav>
    <div class='container'>
        {% block content %}
        {% endblock %}
    </div>
    
</body>
</html>

housei/templates/layout.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <!-- <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'> -->
        <link rel="stylesheet" href="{% static 'css/reset.css' %}"> 
        <link rel="stylesheet" href="{% static 'css/style.css' %}"> 

        <title>豊正中学校1974年度卒業生同窓会</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;600;800&display=swap" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar">
            <div class="nav-item">
		    {% if 'home' in request.path %} 
            <a class='navbar-title current' href='{% url "bbs:home" %}'> ホーム </a>
	    {% else %}
            <a class='navbar-title' href='{% url "bbs:home" %}'> ホーム </a>
	    {% endif %}

            </div>
            <ul class='navbar-nav'>
                    <li class='nav-time'>
                        <span class='navbar-login'>ログイン中:{{ user }} - </span>
                    </li>
                    <li class='nav-item'>
		    {% if 'list' in request.path %} 
                        <a href='{% url "bbs:list" %}' class='list current'>掲示板</a>
	    		{% else %}
                        <a href='{% url "bbs:list" %}' class='list'>掲示板</a>
	    		{% endif %}
                    </li>
                    {% comment %} <!---
                    <li class='nav-item'>
		    {% if 'gyallary' in request.path %} 
                        <a href='{% url "gyallary" %}' class='gyallary current'>ギャラリー</a>
	    		{% else %}
                        <a href='{% url "gyallary" %}' class='gyallary'>ギャラリー</a>
	    		{% endif %}
                    </li>  --->
                    {% endcomment %}
                    <li class='nav-item'>
		    {% if 'logout' in request.path %} 
                        <a href='{% url "logout" %}' class='logout current'>ログアウト</a>
	    		{% else %}
                        <a href='{% url "logout" %}' class='logout'>ログアウト</a>
	    		{% endif %}
                    </li>
                    <li class="nav-item">
		    {% if 'signup' in request.path %} 
			<a href='{% url "accounts:signup" %}' class='signup current'>ユーザー登録</a>
	    		{% else %}
			<a href='{% url "accounts:signup" %}' class='signup'>ユーザー登録</a>
	    		{% endif %}
                    </li>
                    <li class="nav-item">
		    {% if 'login' in request.path %} 
                        <a href='{% url "login" %}' class='login current'>ログイン</a>
	    		{% else %}
                        <a href='{% url "login" %}' class='login'>ログイン</a>
	    		{% endif %}
                    </li>
            </ul>
        </nav>
        <div class="top">
            <h1 class="top-title">豊正中学校1974年度卒業生同窓会サイト</h1>
        </div>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
</body>
</html>